### ISSUE TITLE
Caused by: com.arangodb.ArangoDBException: Response: 400, Error: 1551 - AQL: no value specified for declared bind parameter '0' (while parsing)

### ISSUE THREAD

**Issue by wqxcloud** [arangodb/spring-data-demo#8]
When i run  the demo  some time, it has  this error
Caused by: com.arangodb.ArangoDBException: Response: 400, Error: 1551 - AQL: no value specified for declared bind parameter '0' (while parsing)
at com.arangodb.spring.demo.runner.AQLRunner.run(AQLRunner.java:49) ~[classes/:na]

`2018-11-10 17:34:39.615 ERROR 8392 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.arangodb.spring.demo.DemoApplication.main(DemoApplication.java:43) [classes/:na]
Caused by: com.arangodb.ArangoDBException: Response: 400, Error: 1551 - AQL: no value specified for declared bind parameter '0' (while parsing)
	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:118) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:144) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:47) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:102) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:53) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.internal.ArangoDatabaseImpl.query(ArangoDatabaseImpl.java:197) ~[arangodb-java-driver-4.7.0.jar:na]
	at com.arangodb.springframework.core.template.ArangoTemplate.query(ArangoTemplate.java:342) ~[arangodb-spring-data-3.0.0-RC.1.jar:na]
	at com.arangodb.springframework.repository.query.AbstractArangoQuery.execute(AbstractArangoQuery.java:80) ~[arangodb-spring-data-3.0.0-RC.1.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590) ~[spring-data-commons-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578) ~[spring-data-commons-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.sun.proxy.$Proxy51.getOlderThan(Unknown Source) ~[na:na]
	at com.arangodb.spring.demo.runner.AQLRunner.run(AQLRunner.java:49) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	... 4 common frames omitted`

**Comment by mpv1989** [comment]
This will be fixed with PR #6

**Comment by wqxcloud** [comment]
> This will be fixed with PR #6

ok,thanks your help.
for this condition,when i don't insert age a part of,but others insert age, how can i use AQL to query age > 20（1、include null age；2、not include null age）

**Comment by mpv1989** [comment]
In AQL `null` is lower than `0`. So if you want to query for `age` greater than `20` you have the following options:

### include null age
```
FOR i IN characters
  FILTER i.age > 20 OR i.age == null
  RETURN i
```

### not include null age
```
FOR i IN characters
  FILTER i.age > 20
  RETURN i
```

Keep in mind that `null < 0` which means if you are searching for `age < 20` you will include `age == null` and don't have to filter on `age == null`
```
FOR i IN characters
  FILTER i.age < 20
  RETURN i.age
```
gives you every character with `age` from `null, 0, 1, ...` to `19`

For more informations about types and ordering in AQL, take a look into the [docs](https://docs.arangodb.com/3.3/AQL/Fundamentals/TypeValueOrder.html).

**Comment by wqxcloud** [comment]
> In AQL `null` is lower than `0`. So if you want to query for `age` greater than `20` you have the following options:
> 
> ### include null age
> ```
> FOR i IN characters
>   FILTER i.age > 20 OR i.age == null
>   RETURN i
> ```
> ### not include null age
> ```
> FOR i IN characters
>   FILTER i.age > 20
>   RETURN i
> ```
> Keep in mind that `null < 0` which means if you are searching for `age < 20` you will include `age == null` and don't have to filter on `age == null`
> 
> ```
> FOR i IN characters
>   FILTER i.age < 20
>   RETURN i.age
> ```
> gives you every character with `age` from `null, 0, 1, ...` to `19`
> 
> For more informations about types and ordering in AQL, take a look into the [docs](https://docs.arangodb.com/3.3/AQL/Fundamentals/TypeValueOrder.html).

thank you very much

**Comment by rashtao** [comment]
Closing due to inactivity. Please reopen if the problem still persists.
